// Value construction helpers — avoids writing { tag: '...', value: '...' } by hand.

import type {
  AdminDefineValue,
  BooleanValue,
  CharsetValue,
  CollectionValue,
  DateTimeValue,
  DeleteAttrValue,
  EnumValue,
  IntegerValue,
  IppCollection,
  KeywordValue,
  MimeMediaTypeValue,
  NameWithLanguageValue,
  NameWithoutLanguageValue,
  NaturalLanguageValue,
  NoValueValue,
  NotSettableValue,
  OctetStringValue,
  RangeOfIntegerValue,
  ResolutionValue,
  TextWithLanguageValue,
  TextWithoutLanguageValue,
  UnknownValue,
  UnsupportedValue,
  UriSchemeValue,
  UriValue,
} from './values.js';

export const v = {
  integer:         (value: number):                      IntegerValue         => ({ tag: 'integer', value }),
  boolean:         (value: boolean):                     BooleanValue         => ({ tag: 'boolean', value }),
  enum:            (value: string):                      EnumValue            => ({ tag: 'enum', value }),
  keyword:         (value: string):                      KeywordValue         => ({ tag: 'keyword', value }),
  uri:             (value: string):                      UriValue             => ({ tag: 'uri', value }),
  uriScheme:       (value: string):                      UriSchemeValue       => ({ tag: 'uriScheme', value }),
  charset:         (value: string):                      CharsetValue         => ({ tag: 'charset', value }),
  naturalLanguage: (value: string):                      NaturalLanguageValue => ({ tag: 'naturalLanguage', value }),
  mimeMediaType:   (value: string):                      MimeMediaTypeValue   => ({ tag: 'mimeMediaType', value }),
  text:            (value: string):                      TextWithoutLanguageValue => ({ tag: 'textWithoutLanguage', value }),
  textLang:        (lang: string, text: string):         TextWithLanguageValue    => ({ tag: 'textWithLanguage',    value: { lang, text } }),
  name:            (value: string):                      NameWithoutLanguageValue => ({ tag: 'nameWithoutLanguage', value }),
  nameLang:        (lang: string, text: string):         NameWithLanguageValue    => ({ tag: 'nameWithLanguage',    value: { lang, text } }),
  dateTime:        (value: Date):                        DateTimeValue        => ({ tag: 'dateTime', value }),
  resolution:      (x: number, y: number, unit: 'dpi' | 'dpcm'): ResolutionValue => ({ tag: 'resolution', value: { x, y, unit } }),
  range:           (lower: number, upper: number):       RangeOfIntegerValue  => ({ tag: 'rangeOfInteger', value: [lower, upper] }),
  collection:      (value: IppCollection):               CollectionValue      => ({ tag: 'collection', value }),
  octetString:     (value: Uint8Array):                  OctetStringValue     => ({ tag: 'octetString', value }),
  noValue:         ():                                   NoValueValue         => ({ tag: 'no-value' }),
  unknown:         ():                                   UnknownValue         => ({ tag: 'unknown' }),
  unsupported:     ():                                   UnsupportedValue     => ({ tag: 'unsupported' }),
  notSettable:     ():                                   NotSettableValue     => ({ tag: 'not-settable' }),
  deleteAttribute: ():                                   DeleteAttrValue      => ({ tag: 'delete-attribute' }),
  adminDefine:     ():                                   AdminDefineValue     => ({ tag: 'admin-define' }),
} as const;
